### ISSUE TITLE
WS - GetActivationStatus returns CREATED for any non-existing Activation ID

### ISSUE THREAD

**Issue by Vanyaslav** [lime-company/lime-security-powerauth#29]
Seems like using a new state, which could be introduced for the activation statuses enumeration sounds more correct then getting status CREATED for any input that is not present in DB/Table -> pa_activation.

**Comment by petr-inmite** [comment]
In case of the backend WS, this really should rather raise an exception / SOAP fault.

In case of RESTful API, this should either return "not authenticated" (in case of prepare / sign / remove / vault unlock) or should return random blob on "status"...

**Comment by petr-inmite** [comment]
... it actually makes sense to return "REMOVED" state for this activation. The reason for it is that otherwise, calling server application would have to handle the exception and return a random status blob (I assume that calling with invalid activation ID will be an external event - for example someone fiddling with the RESTful API, not a broken in-house application - and therefore, we need to make the server implementation restrictive in what it returns).
