### ISSUE TITLE
Usage in client-only applications (e.g. single page javascript app)

### ISSUE THREAD

**Issue by martin-dostal** [lime-company/lime-security-powerauth#49]
It would be nice if you can describe if and how PowerAuth can be used in applications without server side (e.g. single page javascript application), which can hardly store any confidential informations.

**Comment by petr-inmite** [comment]
Working on it... ;)

What I don't like about the straight forward approach is that I lose the "multi-factor" bonus I embedded in PowerAuth. Also, PowerAuth assumes having a persistent "activation" which is a bit of an issue (pure OAuth has the same one). It needs more work and bit of a cleverness;)...

**Comment by petr-inmite** [comment]
@martin-dostal After doing some market research, I will close this issue. Let's discuss this in person some time soon, I will try to sum up the information bluntly and briefly here.

As it turns out, the approach I am taking with the banking API is probably the correct one. Based on the multiple company interviews, no-one really cares that much about the "read only" API features (like transaction overviews etc.) Most of the current companies for invoicing / PFM systems are quite happy with the current means, such as with processing the e-mails from the bank. Even some fresh and young startups are preferring this approach.

IMO Banking API must be secure enough to be able to process payments. This is the key and new feature it can introduce. As a result, it does not have to be that much "convenient" (unless you need students doing their school projects with banking data) or work in insecure environments such as JavaScript only apps.

Also, by interviewing real end users, they are really scared about providing their data to any third party, so I will have to improve the end-to-end encryption (by using the transport key to encrypt the communication from the bank to the client device, so that any intermediate system - including us - is unable to intercept sensitive data).
