### ISSUE TITLE
Swapped key and message in HMAC calculations

### ISSUE THREAD

**Issue by hvge** [lime-company/lime-security-powerauth#52]
In 

> public String computeSignature(byte[] data, List<SecretKey> signatureKeys, int CTR)

 you're using key instead of message (and vice versa) in some HMAC calculations. For example, 

```
KEY_DERIVED_CURRENT = Mac.HMAC_SHA256(KEY_SIGNATURE, CTR);
SIGNATURE_LONG      = Mac.HMAC_SHA256(DATA, KEY_DERIVED);
KEY_DERIVED         = Mac.HMAC_SHA256(KEY_DERIVED, KEY_DERIVED_CURRENT);

// ...and definitions.md says:
Mac.hmacSha256(SharedKey key, byte[] message) ...
```

The calculation of SIGNATURE_LONG in the documentation doesn't make sense at all, but fortunately the reference java impl. is correct. I think that we should always use key as key and message as message.

**Comment by petr-inmite** [comment]
The code in this chapter is still written in pure Java, not a pseudocode. Thus the key and data is inverted there.

From a crypto point of view, swapping a key and data in HMAC is not a huge issue, since:

`HMAC(K, m) = H ((K ^ opad) + H ( (K ^ ipad) + m))` [source](https://en.wikipedia.org/wiki/Hash-based_message_authentication_code)

But it could be made more consistent... Let's make this arrangement:

- Everything that is used as a "key" in PowerAuth will enter the "key" part of the HMAC (despite the fact it technically might be data in that case, or despite the fact interpretation might not matter).
- Everything else (like counters, data, constants, etc.) goes in the "data" part of the HMAC.

Does this make sense, Juraj?

**Comment by hvge** [comment]
Yes, that make sense. I agree that the most important issue here is that current specification and reference implementation confuses developers. It is very real, based on my own experience.

**Comment by petr-inmite** [comment]
OK, I will rewrite the code using the definition:

`byte[] signature = Mac.hmacSha256(SharedKey key, byte[] message)`
